### ISSUE TITLE
Unable to find contact information

### ISSUE THREAD

**Issue by C-Otto** [fink/fink-mirrors#7]
I am an administrator of one of your mirrors, and neither in my mail archive nor on your homepage I can locate any contact information. At least the "become a mirror" page should provide that. Please tell me how I can get into touch with you regarding mirror issues.

**Comment by akhansen** [comment]
I'd recommend emailing fink-core@lists.sourceforge.net.  I don't actually know where the "become a mirror" page you're referencing actually resides.

**Comment by C-Otto** [comment]
The link is on http://finkmirrors.net/.

Where can I find documentation for the list you mentioned?

**Comment by dak180** [comment]
I would also recommend the fink-mirrors@lists.sourceforge.net list; also the latest version of the mirror scripts are in https://github.com/fink/scripts/pull/37 until @TheSin- can spare the time to update the main server with the new path/names.

**Comment by C-Otto** [comment]
That's another address. As said, I can't find this in a suitable place. Could you please add it to your README, the homepages, or any other place that prospective mirror admins might look at?

**Comment by C-Otto** [comment]
I did not get any response, although I wrote to both lists and waited a few days. Furthermore, I still can't find a contact address on the sites. Could you please:
 - comment on this
 - fix this issue by writing down a contact address somewhere suitable
 - poke someone to reply to my mail?

Thank you!

**Comment by akhansen** [comment]
dak180 is the only Fink developer currently subscribed to fink-mirrors.

Your message to fink-core got held longer in the non-subscriber moderation queue than usual, but has been released so that now people will actually see it.  My apologies for that.

**Comment by dak180** [comment]
@C-Otto I did [respond to you on fink-mirrors](http://sourceforge.net/p/fink/mailman/fink-mirrors/thread/D9083E1E-03DF-4039-B397-4D623BBB1471%40users.sourceforge.net/#msg34771813) only 2 hours or so after your initial message to the list.
As far as points of contact go I will echo @akhansen's feelings on the list being the best place to email so any of the team members can see it; that said though, I imagine you will mostly be talking with @TheSin- and myself since @TheSin- is our primary server admin and I have been rewriting most of the scripts that both the main server and mirrors should use to keep info and src files up to date.

**Comment by akhansen** [comment]
Also, for a more focused discussion, https://github.com/fink/scripts is the github repository which actually has the server-side scripts (and other things--it's kind of a catch-all location).

"fink-mirrors" here is really just a package which provides the available download locations for individual fink users.

**Comment by C-Otto** [comment]
@dak180 that mail did not reach me, are you sure you replied to me (or ftp@halifax.rwth-aachen.de)? I don't know what you wrote. But I'll note to use the lists, and hope the messages are read.

@akhansen Should I open another ticket?

**Comment by dak180** [comment]
@C-Otto I am guessing that you were not yet subscribed to the mirror list then since my reply was sent there and not to you directly.

**Comment by C-Otto** [comment]
@dak180 OK, could you reply/forward to me? I still don't intend to subscribe to a list I don't want to read.

**Comment by akhansen** [comment]
I added Fink Project contact information in d6a2d00ecbbb8a5ffa0398288a540352aa648a20 .  That was an excellent idea, thanks!
