### ISSUE TITLE
No mirror worked.

### ISSUE THREAD

**Issue by EcnuTengfei** [fink/fink-mirrors#9]
Hi, when I run "fink update", the message is
"usr/bin/rsync -az -q  rsync://distfiles.master.finkmirrors.net/finkinfo//TIMESTAMP /sw/fink/TIMESTAMP.tmp
rsync: failed to connect to distfiles.master.finkmirrors.net: Connection refused (61)
rsync error: error in socket IO (code 10) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-51/rsync/clientserver.c(106) [receiver=2.6.9]
### execution of /usr/bin/rsync failed, exit code 10
Failed to fetch the timestamp file from the rsync server: rsync://distfiles.master.finkmirrors.net/finkinfo/.  Check the error messages above.

(1)	Give up
(2)	Retry the same mirror
(3)	Retry another mirror
"
At last, it shows:
"No mirror worked. This seems unusual, please submit a short summary of this event to mirrors@finkmirrors.net"

What I should do for that? 
Is it the 873 port problem of the firewall?

Thank you

**Comment by akhansen** [comment]
It's pretty common for firewall setups to exclude port 873.  If your administrator won't open that port for you, then I'd recommend using git selfupdate over HTTPS instead, since that port is usually open for most firewall setups.

**Comment by EcnuTengfei** [comment]
@akhansen Thank you.   Yes, you are right. This is the port problem. It is ok when I am at home.
